# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'touchSound' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for touchSound
  pod 'Socket.IO-Client-Swift', '7.0.3'
  target 'touchSoundTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'touchSoundUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
